spring.application.name=api-gateway
server.port=${PORT:8080}

auth.service.url=https://auth-service-w1l1.onrender.com
quantity.service.url=https://quantity-service-gzo4.onrender.com
history.service.url=https://history-service-cpvn.onrender.com

# admin.service.url is optional - leave empty if not deployed
admin.service.url=

logging.level.com.apps.gateway=INFO