spring.application.name=quantity-service
#server.port=8083

server.port=${PORT:8080}

history.service.url=http://localhost:8084
auth.service.url=http://localhost:8081

logging.level.com.apps.quantity=INFO

