spring.application.name=quantity-service
server.port=${PORT:8080}

history.service.url=${HISTORY_SERVICE_URL:https://history-service-cpvn.onrender.com}
auth.service.url=${AUTH_SERVICE_URL:https://auth-service-w1l1.onrender.com}

logging.level.com.apps.quantity=INFO

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.deserialization.fail-on-unknown-properties=false
