spring.application.name=quantity-service
server.port=8083

history.service.url=http://localhost:8084
auth.service.url=http://localhost:8081

logging.level.com.apps.quantity=INFO

# H2 Database Config
spring.datasource.url=jdbc:h2:mem:quantitydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA Config
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
