spring.application.name=quantity-service
#server.port=8083

server.port=${PORT:8080}

history.service.url=https://history-service-cpvn.onrender.com
#http://localhost:8084

auth.service.url=https://auth-service-w1l1.onrender.com
#http://localhost:8081

logging.level.com.apps.quantity=INFO

